# Generated by Django 5.2.1 on 2025-05-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetup", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_organizer",
            field=models.BooleanField(
                default=False, verbose_name="Является организатором"
            ),
        ),
    ]
